version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  reviewers:
  - MagicMarvMan
  assignees:
  - MagicMarvMan
  ignore:
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: svgo
    versions:
    - 1.3.2
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.1.0
    - 2.2.0
    - 2.2.1
    - 2.2.2
  - dependency-name: markdownlint-cli
    versions:
    - 0.26.0
    - 0.27.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: unexpected
    versions:
    - 12.0.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: assetgraph-builder
    versions:
    - 8.1.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: eslint
    versions:
    - 5.16.0
